package br.com.mdsgpp.guiaescolaideal.model;

public enum Equipamento {
	DVD, IMPRESSORA, APARELHO_SOM, PROJETOR_MULTIMEDIA, FAX, MAQUINA_FOTOGRAFICA_OU_FILMADORA, PARABOLICA, FILMADORA, COPIADORA;

}
